kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
        - name: 8443-tcp
          port: 8443
          protocol: TCP
          targetPort: 8443
      selector:
        deploymentconfig: ${NAME}
      sessionAffinity: None
    metadata:
      name: ${NAME}
      labels:
        deploymentconfig: ${NAME}
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: ${NAME}
      labels:
        deploymentconfig: ${NAME}
    spec:
      triggers:
        - type: "ConfigChange"
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            from:
              kind: "ImageStreamTag"
              name: ${NAME}:${IMAGE_TAG}
              namespace: ${BUILD_NAMESPACE}
            containerNames:
              - ${NAME}
      replicas: 1
      revisionHistoryLimit: 5
      selector:
        deploymentconfig: ${NAME}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            deploymentconfig: ${NAME}
        spec:
          volumes:
            - name: site-data-volume
              configMap:
                name: subpath-env
          containers:
            - image: >-
                image-registry.openshift-image-registry.svc:5000/${BUILD_NAMESPACE}/${NAME}
              volumeMounts:
                - name: site-data-volume
                  mountPath: /var/site_data
              imagePullPolicy: Always
              name: ${NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
              resources:
                limits:
                  cpu: 500m
                  memory: 2Gi
                requests:
                  cpu: 250m
                  memory: 512Mi
              livenessProbe:
                exec:
                  command:
                    - php
                    - /var/www/html/artisan
                    - dusk:chrome-driver
                    - --detect
                periodSeconds: 30
                initialDelaySeconds: 10
                timeoutSeconds: 15
                successThreshold: 1
                failureThreshold: 2
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      host: ${NAME}-${NAMESPACE}.apps.silver.devops.gov.bc.ca
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${NAME}
        weight: 100
      wildcardPolicy: None
    metadata:
      name: ${NAME}
      labels:
        deploymentconfig: ${NAME}
parameters:
  - name: NAME
    required: true
    description: some desc for this component
  - name: IMAGE_TAG
    required: true
    description: some line to describe the image_tag_x parameter
  - name: BUILD_NAMESPACE
    required: true
    description: some line to describe the image_tag_x parameter
  - name: NAMESPACE
    required: true
    description: some line to describe the image_tag_x parameter
